"""Close the recorded campaign with read-only output checks and a public report."""
from pathlib import Path
import json
import urllib.request
from decimal import Decimal
from datetime import datetime, timezone

SIM = Path(__file__).resolve().parent.parent
RUN = 'CHIP-WITHDRAW-01-R4'
ROOT = SIM / 'evidence' / RUN

def read(path):
    return json.loads(path.read_text(encoding='utf-8'))

def write(path, value):
    path.write_text(json.dumps(value, indent=2) + '\n', encoding='utf-8')

state = read(ROOT / 'run-state.json')
if state.get('stopped') or state['completed'][-1] != 'close':
    raise SystemExit('Campaign has not passed closure.')

checks = []
def rpc(command, port=9105):
    from urllib.parse import quote
    with urllib.request.urlopen('http://127.0.0.1:' + str(port) + '/' + quote(command, safe=''), timeout=20) as response:
        result = json.load(response)
    checks.append({'at': datetime.now(timezone.utc).isoformat(), 'port': port,
                   'command': command, 'response': result})
    if result.get('status') is not True:
        raise RuntimeError('Read-only closing query failed.')
    return result['response']

owner = []
for coinid in state['coins']['payouts']:
    rows = rpc('coins relevant:true sendable:true coinid:' + coinid)
    if len(rows) != 1 or rows[0]['spent']:
        raise RuntimeError('Owner payout is not sendable.')
    owner.append(rows[0])
write(ROOT / 'owner-spendability.json', {'at': datetime.now(timezone.utc).isoformat(),
      'method': 'Confirmed payout coins are returned by the owning node sendable:true filter.',
      'payouts': owner, 'total': str(sum(Decimal(x['tokenamount']) for x in owner)), 'pass': True})

native = []
for phase in ('d1a', 'd1b'):
    for output in state['steps'][phase]['canonical']['outputs'][1:]:
        rows = rpc('coins relevant:true sendable:true coinid:' + output['coinid'])
        if len(rows) != 1 or rows[0]['tokenid'] != '0x00' or rows[0]['spent']:
            raise RuntimeError('Returned helper native coin unavailable.')
        native.append(rows[0])
total = sum(Decimal(x['amount']) for x in native)
if total != Decimal('0.00000010'):
    raise RuntimeError('Helper native conservation failed.')
write(ROOT / 'native-return-check.json', {'at': datetime.now(timezone.utc).isoformat(),
      'coins': native, 'total': str(total), 'pass': True,
      'meaning': 'All ten native helpers returned to the laboratory wallet, no helper burn.'})
write(ROOT / 'closing-readonly-commands.json', checks)

for run in ('CHIP-WITHDRAW-01-R1', 'CHIP-WITHDRAW-01-R2', 'CHIP-WITHDRAW-01-R3', RUN):
    folder = SIM / 'evidence' / run
    report = read(folder / 'local-preflight/results.json')
    write(folder / 'local-preflight-summary.json', {key: value for key, value in report.items() if key != 'results'} | {
        'results': [{key: value for key, value in result.items() if key != 'trace'} for result in report['results']],
        'note': 'Verbose traces remain in the local results. Frozen source and formal exported transactions are published separately.'})

honest = []
for phase in ('d1a', 'd2a', 'd1b', 'd2b'):
    result = state['steps'][phase]
    canonical = read(ROOT / (phase + '-canonical.json'))
    limits = canonical['block']['header']['magic']
    size = canonical['transaction']['size']
    if size > int(limits['currentmaxtxpowsize']):
        raise RuntimeError('Actual TxPoW exceeds recorded consensus size limit.')
    honest.append(f"| {phase} | {result['canonical']['block']} | {size:,} | {result['exportBytes']:,} | `{result['canonical']['txpowid']}` |")

negative_names = ('bad-secret', 'bad-complement', 'release-redirect', 'payout-redirect',
                  'payout-overpay', 'reserve-skim', 'replay-voucher1', 'fake-release')
negative = []
for name in negative_names:
    result = state['steps'][name]
    if result['posted'] or not result['deleted'] or result['flags'] != {
            'basic': True, 'signatures': True, 'mmrproofs': True, 'scripts': False}:
        raise RuntimeError('Refusal result differs from protocol: ' + name)
    negative.append(f"| {name} | covenant refused | never posted | [result]({name}-result.json), [export](exports/{name}.hex) |")

duration = (datetime.fromisoformat(read(ROOT / 'fixture-block.json')['at'].replace('Z', '+00:00')),
            datetime.fromisoformat(read(ROOT / 'closure.json')['at'].replace('Z', '+00:00')))
minutes = (duration[1] - duration[0]).total_seconds() / 60
text = f"""# Complete cumulative chip withdrawal: mainnet closure

**PASS, {RUN}, 2026-10-08.** Complete D1 signature verification and D2 vault
payout transactions settled on Minima mainnet using signatures generated by the
current Java Card applet in jCardSim. No signature or covenant check was disabled.
This is L2 evidence for the named candidate withdrawal paths, under the assumed
hardware and certification guarantees. It is not physical-chip validation.

The first cumulative authorisation was 250 units. The second was 290 units, and
the vault correctly paid only its 40-unit increment. Both registered lab peers
observed the same canonical blocks with at least one confirmation each. Closing
reads show **290 paid + 310 remaining = 600 funded**, account cumulative debit 290,
highest redeemed key index 2, and both owner payout coins sendable. All ten native
helper coins returned to the laboratory wallet, 0.00000010 MINIMA, without burn.

## Honest withdrawal transactions

| Transaction | Mainnet block | Actual TxPoW bytes | Export bytes | Mined TxPoW ID |
|---|---:|---:|---:|---|
{chr(10).join(honest)}

Active block limits were **65,536 TxPoW bytes** and **1,024 KISS instructions per
script**. The account verifier used 377 instructions, each of the five helpers 800,
the release covenant 52, and the vault payout 157 in replay of the actual builder
contents through the same node jar. Full node validation passed basic, ordinary
signatures, MMR proofs and scripts for every honest control. LX16 authentication
lives in the script check; the ordinary-signature flag alone is not chip authentication.

## Preserved refused attempts

All eight passed basic construction, ordinary-signature and MMR checks while
failing the expected covenant clause. They were exported and deleted, never posted.
Every result preserves the full validator, failing input/clause and unchanged
unspent-input observations on both nodes.

| Attempt | Result | Publication | Evidence |
|---|---|---|---|
{chr(10).join(negative)}

The fake-release attempt substituted the continued account marker for the genuine
release coin. Both the account and vault refused it. Replay reused voucher 1
against the continued account after the first payout; the key-index guard refused it.

## Source, setup and reproduction

- [Prospective protocol, version 2](../../docs/CHIP-WITHDRAW-01-R4.md).
- [Frozen fixtures and source hashes](fixture-block.json), [exact frozen source](captured-sources/), [deployed lab scripts](kiss/).
- [Machine-readable closure and final coins on both peers](closure.json).
- [Owner payout spendability](owner-spendability.json), [native helper return](native-return-check.json).
- [63-case local preflight](local-preflight-summary.json): 63 expected per-input
  outcomes, including the newer-authorisation-first scenario. This part is L0;
  the out-of-order scenario was not separately mined.
- [R3 preparation and builder stop](../CHIP-WITHDRAW-01-R3/CLOSURE_REPORT.md).
  Setup, vendor-signed registration and funding were already canonical at blocks
  2355455, 2355457 and 2355459. R4 inherited those unredeemed fixtures explicitly;
  it did not claim to recreate them as new R4 transactions.

The laboratory vendor signed registration of the simulated applet's public-key
tree. The entire unique marker supply was locked in the registration gate.
Authentication of that lab registration is demonstrated; certification of a
physical chip and its approved software remains future work.

The lab tree registered eight public keys supplied by the current simulated
applet and redeemed indices 1 and 2. The production-sized tree and key-renewal
flows are outside this campaign. The complete withdrawal claim applies to the
frozen test configuration, not every possible key-tree or account branch.

Use the captured source, the recorded node jar hash/version, and the signed/exported
transaction bytes to reconstruct witness/amount checks. Create a fresh purpose-created
generation for an independent on-chain reproduction, rather than reposting spent
exports or importing laboratory wallet keys. Node binaries and compiled SDK/classes
are excluded from the public documentation snapshot. Complete verbose command logs
and traces remain in the local evidence; compact reports preserve the useful outcomes.

## Findings, limitations and next decision

The named Minima-side withdrawal feasibility question is answered positively.
This corrects the earlier status that complete chip-authorised withdrawal had not
been mined. The cumulative D1 branch and sequential D2 settlements are now tested
in these baseline variants, rather than inferred from the old signature-core dry runs.

The deployed app and its software-trusting vault were not upgraded. Physical
card installation, timing, interruption/atomicity and randomness checks, secure
provisioning and certification, production app integration, complete other-branch
and long-term availability validation, and independent LX16/protocol review remain.
These tests do not prove hardware key non-extraction or that a compromised vendor
cannot certify bad software. The hardware premise remains explicit.

Two earlier defects were recorded without posting invalid transactions: R2 used
the mint placeholder token ID instead of the confirmed token identity; R3 called
txnbasics twice and duplicated proofs. Corrective runs had new identities/hashes.
No platform-limit breach occurred. All sources and negative results remain available.

Formal R4 execution took approximately **{minutes:.1f} minutes**, four honest
withdrawal transactions and eight unposted refused attempts. Preparation included
two valueless token mints and three canonical setup controls. The founder supplied
0.000001 MINIMA to the isolated lab; tiny native colouring created the tokens, with
no transaction burn and all helper native amounts returned.

**Recommendation:** continue to a real two-card laboratory validation and app
integration campaign, retaining the current production limitations. Founder review
is still needed before promoting this evidence into the binding knowledge base,
protocol documentation map and handshake capsule. No economic policy or production
release was approved. The current capsule's authority sources remain unchanged.
"""
(ROOT / 'CLOSURE_REPORT.md').write_text(text, encoding='utf-8')
(ROOT / 'README.md').write_text('# ' + RUN + '\n\n'
    'Status: **passed**. [Mainnet closure report](CLOSURE_REPORT.md).\n\n'
    'Complete cumulative withdrawals settled with current simulated-applet signatures. '
    'All eight attacks were refused. Frozen source, transactions and canonical receipts are included. '
    'Hardware security and production integration remain unvalidated.\n', encoding='utf-8')
print(json.dumps({'status': 'pass', 'formal_minutes': round(minutes, 1),
      'honest_withdrawals': len(honest), 'refusals': len(negative),
      'owner_paid': '290', 'reserve_remaining': '310', 'helpers_returned': str(total)}))
